// Centralized game constants — single source of truth for all tunable values.

export const CONFIG = Object.freeze({
  world: {
    size: 220,
    segments: 110,
    boundaryPadding: 4,
    maxWorld: 107,
    fog: { near: 40, far: 260, color: 0x7aa4d6 },
    hazardZones: [
      { x: -38, z: 34, radius: 10, dps: 7 },
      { x: 45, z: -22, radius: 12, dps: 8 },
      { x: 6, z: 48, radius: 8, dps: 9 },
    ],
    lowTerrainThreshold: -1.6,
    lowTerrainDps: 6,
    dayNightSpeed: 0.08,
  },

  player: {
    baseSpeed: 8,
    baseSprintSpeed: 13,
    baseJumpPower: 9,
    gravity: 24,
    height: 1.6,
    fallDamageThreshold: 13.5,
    fallDamageMultiplier: 5.5,
    sprintStaminaCost: 20,
    jumpStaminaCost: 15,
    staminaRegenMoving: 12,
    staminaRegenIdle: 22,
    collectRadius: 1.5,
    projectileHitRadius: 1.2,
  },

  camera: {
    fov: 70,
    near: 0.1,
    far: 500,
    distance: 6.8,
    aimDistance: 3.4,
    minDistance: 1.25,
    height: 2.6,
    lookHeight: 1.6,
    shoulderOffset: 1.05,
    positionLerp: 12,
    aimPositionLerp: 16,
    minPitch: -1.05,
    maxPitch: 0.72,
    collisionPadding: 0.25,
  },

  weapons: {
    rifle: {
      id: "rifle",
      label: "Rifle",
      damage: 18,
      range: 30,
      cooldown: 0.26,
      projectileSpeed: 52,
      projectileLife: 1.2,
      projectileRadius: 0.08,
      projectileColor: 0xfff2a8,
      toneImpact: 760,
      toneShot: 300,
    },
    shotgun: {
      id: "shotgun",
      label: "Shotgun",
      damage: 8,
      range: 18,
      cooldown: 0.85,
      pellets: 6,
      spread: 0.08,
      projectileSpeed: 42,
      projectileLife: 0.45,
      projectileRadius: 0.06,
      projectileColor: 0xffc78b,
      toneImpact: 690,
      toneShot: 250,
    },
    pulse: {
      id: "pulse",
      label: "Pulse",
      damage: 11,
      range: 26,
      cooldown: 0.14,
      projectileSpeed: 60,
      projectileLife: 0.9,
      projectileRadius: 0.065,
      projectileColor: 0x8fd6ff,
      toneImpact: 820,
      toneShot: 340,
    },
  },

  weaponOrder: ["rifle", "shotgun", "pulse"],

  enemies: {
    bruiser: {
      color: 0xc45454,
      emissive: 0x2a1010,
      speed: 4.2,
      maxHealth: 42,
      attackRange: 2.2,
      attackDamage: 8,
      attackCooldown: 1.0,
      detectionRange: 22,
      rewardScore: 6,
      rewardXp: 22,
      respawnDelay: 20,
      size: 0.85,
    },
    shooter: {
      color: 0x4f7acb,
      emissive: 0x0f1733,
      speed: 3.8,
      maxHealth: 32,
      attackRange: 24,
      attackDamage: 7,
      attackCooldown: 1.4,
      detectionRange: 28,
      rewardScore: 8,
      rewardXp: 28,
      respawnDelay: 24,
      preferredRange: 13,
      size: 0.75,
      projectileSpeed: 18,
    },
  },

  collectibles: {
    spawnCount: 45,
    common: { score: 1, xp: 10, respawn: 18 },
    rare: { score: 3, xp: 28, respawn: 30 },
    heal: { score: 2, xp: 14, heal: 12, respawn: 24 },
  },

  progression: {
    baseXp: 70,
    xpPerLevel: 35,
    maxLevel: 50,
    upgradeValues: {
      speed: { baseSpeed: 0.7, sprintSpeed: 1.1 },
      jump: { jumpPower: 0.55 },
      stamina: { maxStamina: 15 },
    },
  },

  objectives: {
    baseTarget: 3,
    baseTimeLimit: 45,
    timeLimitDecay: 2,
    minTimeLimit: 24,
    baseRewardScore: 10,
    rewardScorePerTier: 5,
    baseRewardXp: 40,
    rewardXpPerTier: 14,
  },

  audio: {
    masterVolume: 0.6,
    ambientFreq: 86,
    ambientBaseGain: 0.02,
    ambientVolumeScale: 0.03,
    tones: {
      levelUp: { freq: 660, duration: 0.2, type: "triangle", volume: 0.14 },
      kill: { freq: 980, duration: 0.12, type: "triangle", volume: 0.12 },
      damage: { freq: 165, duration: 0.09, type: "square", volume: 0.07 },
      hazardDamage: { freq: 180, duration: 0.08, type: "square", volume: 0.06 },
      fallDamage: { freq: 150, duration: 0.2, type: "sawtooth", volume: 0.1 },
      death: { freq: 120, duration: 0.3, type: "square", volume: 0.13 },
      objectiveComplete: { freq: 930, duration: 0.2, type: "triangle", volume: 0.16 },
      objectiveFail: { freq: 220, duration: 0.25, type: "sawtooth", volume: 0.12 },
      collect: { freq: 520, duration: 0.15, type: "triangle", volume: 0.12 },
      collectRare: { freq: 820, duration: 0.15, type: "triangle", volume: 0.12 },
    },
  },

  settings: {
    defaultSensitivity: 1,
    minSensitivity: 0.4,
    maxSensitivity: 2.2,
    defaultVolume: 0.4,
    defaultMute: false,
  },

  rendering: {
    maxPixelRatio: 2,
    shadowMapSize: 2048,
    maxDeltaTime: 0.05,
  },
});
