export const GAME_CONFIG = Object.freeze({
  character: {
    movement: {
      walkSpeedThreshold: 0.18,
      jogSpeedThreshold: 0.52,
      sprintSpeedThreshold: 0.82,
      accelGround: 12,
      accelAir: 4,
      groundDrag: 7,
    },
    animation: {
      locomotionBlendSpeed: 10,
      aimBlendSpeed: 12,
      torsoYawFollow: 8,
      landingRecoverSeconds: 0.2,
      walkCycleBase: 2.1,
      walkCycleSpeedFactor: 1.05,
      bobAmplitude: 0.03,
      weaponBobAmplitude: 0.015,
      weaponSwayAmplitude: 0.02,
    },
    camera: {
      swayAmplitude: 0.04,
      swayFrequency: 3.4,
      springStiffness: 20,
      springDamping: 10,
      adsDampingMultiplier: 1.25,
      kickRecovery: 7,
      weaponKickScale: 0.035,
      maxKick: 0.1,
      landingImpulseScale: 0.012,
      landingImpulseMax: 0.32,
      recoilProfiles: {
        default: { recoil: 0.38, camKick: 1, yawJitter: 1 },
        rifle: { recoil: 0.38, camKick: 1, yawJitter: 1 },
        smg: { recoil: 0.28, camKick: 0.75, yawJitter: 1.4 },
        shotgun: { recoil: 0.52, camKick: 1.2, yawJitter: 1.1 },
        sniper: { recoil: 0.72, camKick: 1.8, yawJitter: 0.45 },
        flamethrower: { recoil: 0.2, camKick: 0.35, yawJitter: 0.9 },
      },
    },
  },
  save: {
    version: 5,
  },
  debug: {
    enabledByDefault: false,
    refreshInterval: 0.1,
  },
  combat: {
    flamethrower: {
      treeIgniteCooldown: 0.65,
      treeIgniteRadius: 0.85,
    },
  },
  world: {
    size: 360,
    freeway: {
      enabled: false,
      deckHeight: 16,
      deckWidth: 14,
      edgePadding: 24,
      deckThickness: 1.15,
      pillarSpacing: 18,
      rampHalfWidth: 5,
      rampRun: 42,
    },
  },
  vehicles: {
    enterRange: 3.2,
    hintRange: 2.9,
    hintCooldown: 2.8,
    explosions: {
      criticalHealthRatio: 0.25,
      criticalDelayMin: 0.7,
      criticalDelayMax: 1.8,
      burnDurationMin: 1.4,
      burnDurationMax: 2.6,
      wreckTransitionSeconds: 0.45,
      radius: 7.5,
      maxDamage: 56,
      chainVehicleDamageMultiplier: 0.72,
      playerDamageMultiplier: 0.95,
      impulse: 8,
      respawnAfterSeconds: 0,
    },
    mountedWeapon: {
      damage: 16,
      range: 72,
      fireRate: 8,
      spread: 0.03,
      hitRadius: 0.22,
      heatPerShot: 0.1,
      coolPerSecond: 0.24,
      maxHeat: 1,
      overheatDuration: 1.35,
      resumeHeatThreshold: 0.34,
    },
    combat: {
      repairAmount: 48,
      repairRange: 4.2,
      destroyRecoverySeconds: 8,
      projectileHitRadius: 1.4,
    },
    drift: {
      tiers: [
        { name: "Bronze", bank: 60 },
        { name: "Silver", bank: 160 },
        { name: "Gold", bank: 320 },
        { name: "Apex", bank: 520 },
      ],
    },
  },
});
